# Executable should be a full path
executable=/home/jsingh/projects/fastlm/src/data/datasets/prepare_nemotron_cc_sample.sh

# Logs
LOGS_DIR=/fast/jsingh/logs/fastlm/tokenize_nemotron_160BT/

error = $(LOGS_DIR)/err/job.$(Cluster).$(Process).err
output = $(LOGS_DIR)/out/job.$(Cluster).$(Process).out
log = $(LOGS_DIR)/log/job.$(Cluster).$(Process).log

# Job requirements
request_memory = 32G
request_cpus = 8
request_gpus = 0

queue 1
