SCALING_LADDER = {
  'models': {
    '20M': {
      'total_params': 15e5,
      'non_embedding_params': 2e6,
      'd_model': 256,
      'n_layers': 8,
      'n_heads': 4,
      'dp': 4,
      'max_tokens_billions': 15,
      'num_token_budgets': 5,
      'beta2': 0.99,
    },
    '50M': {
      'total_params': 45869568,
      'non_embedding_params': 26552832,
      'd_model': 384,
      'n_layers': 12,
      'n_heads': 8,
      'dp': 4,
      'max_tokens_billions': 15,
      'num_token_budgets': 5,
      'beta2': 0.99,
    },
    '150M': {
      'total_params': 84494848,
      'non_embedding_params': 58739200,
      'd_model': 512,
      'n_layers': 16,
      'n_heads': 8,
      'dp': 4,
      'max_tokens_billions': 15,
      'num_token_budgets': 5,
      'beta2': 0.95,
    },
    '300M': {
      'total_params': 220338048,
      'non_embedding_params': 181704576,
      'd_model': 768,
      'n_layers': 22,
      'n_heads': 8,
      'dp': 4,
      'max_tokens_billions': 15,
      'num_token_budgets': 5,
      'beta2': 0.95,
    },
  },
  'batch_sizes': [16, 32, 64, 128, 256, 512],
  'batch_size_vs_token_budget_strategy': {
    'staggered_grid': {
      '0.5B': [16, 32, 64, 128],
      '1.0B': [16, 32, 64, 128],
      '3.0B': [32, 64, 128, 256],
      '7.5B': [64, 128, 256, 512],
      '15B': [64, 128, 256, 512],
    },
    'staggered_runs': {
      16: '1.0B',
      32: '3.0B',
      64: '15B',
      128: '15B',
      256: '15B',
      512: '15B',
    },
  },
  'learning_rates': [0.0025, 0.005, 0.01, 0.02, 0.04, 0.08],
  'gradient_accumulation_steps': [1, 2, 4, 8],
  'warmup_steps': 2000,
  'seq_len': 2048,
  'throughput_analysis_steps': 100,
}
DEFAULT_CONFIG = {
  'deterministic': False,
  'seed': 123,
  # DATA
  'trainset_path': '/fast/jsingh/data/nemotron-cc-sample-mtsynth/tokenized_gpt2/ctx_2048/train',
  'vocab_size': 50304,
  'seq_len': 2048,
  'intra_doc_masking': False,
  'sampler': 'sequential',
  'sampler_seed': None,
  'num_workers': 4,
  'eval': True,
  'validset_path': '/fast/jsingh/data/nemotron-cc-sample-mtsynth/tokenized_gpt2/ctx_2048/valid',
  'eval_every_steps': 50,
  # MODEL
  'model': 'transformer',
  'd_model': 256,
  'mlp_class': 'glu',
  'expand': '3.0',
  'n_layers': 8,
  'n_heads': 4,
  'rms_norm': True,
  'tie_embeddings': True,
  'torch_compile': True,
  'token_mixer': 'attn',
  'hybrid_mixer_ratio': 1,
  'layer_norm_scaling': False,
  'residual_connection': 'add',
  'attn_gate': True,
  'attn_qk_norm': True,
  'gdn_conv_size': 4,
  'gdn_gate': True,
  'gdn_neg_eigval': True,
  # TRAINING
  'steps_budget': -1,
  'chinchilla_token_multipler': 2.5,
  'micro_batch_size': 32,
  'grad_accumulation_steps': 1,
  'dtype': 'bfloat16',
  # OPTIMIZER
  'optim': 'adamw',
  'fused_optim': True,
  'lr': 1e-3,
  'weight_decay': 0.1,
  'beta1': 0.9,
  'beta2': 0.95,
  'grad_clip': 1.0,
  # SCHEDULER
  'scheduler': 'warmup_cosine',
  'warmup_steps': 0.1,
  'cooldown_steps': 0,
  'lr_start': 0.0,
  'lr_end': 1e-5,
  'lr_end_pct': None,
  # EXPERIMENT
  'log_every_steps': 1,
  'print_progress': True,
  'use_wandb': False,
  'wandb_mode': 'online',
  'wandb_project': 'hparam-sweep',
  'wandb_entity': 'msc-thesis-jaisidh',
  'wandb_dir': '/fast/jsingh/projects/fastlm/wandb',
  'wandb_run_name': 'attn-20M',
  'exp_name': 'hparam-sweep_attn-20M',
  'out_dir': '/fast/jsingh/projects/fastlm/experiment_logs',
  'over_write': True,
  'resume': False,
  'resume_step': None,
  'resume_exp_name': None,
  'save_last_checkpoint': False,
  'save_intermediate_checkpoints': False,
  'save_every_steps': 500,
}
