SCALING_LADDER = {
  'models': {
    '20M': {
      'total_params': 15e5,
      'non_embedding_params': 2e6,
      'd_model': 256,
      'n_layers': 8,
      'n_heads': 4,
      'dp': 4,
      'peak_mbs': {
        'mpi': 32,
        'capella': 32,
        'alpha': 16,
      },
      'max_tokens_billions': 15,
      'num_token_budgets': 5,
      'beta2': 0.99,
    },
    '50M': {
      'total_params': 45869568,
      'non_embedding_params': 26552832,
      'd_model': 384,
      'n_layers': 12,
      'n_heads': 8,
      'dp': 4,
      'peak_mbs': {
        'mpi': 32,
        'capella': 32,
        'alpha': 16,
      },
      'max_tokens_billions': 15,
      'num_token_budgets': 5,
      'beta2': 0.99,
    },
    '150M': {
      'total_params': 84494848,
      'non_embedding_params': 58739200,
      'd_model': 512,
      'n_layers': 16,
      'n_heads': 8,
      'dp': 8,
      'peak_mbs': {
        'mpi': 16,
        'capella': 16,
        'alpha': 8,
      },
      'max_tokens_billions': 15,
      'num_token_budgets': 5,
      'beta2': 0.95,
    },
    '300M': {
      'total_params': 220338048,
      'non_embedding_params': 181704576,
      'd_model': 768,
      'n_layers': 22,
      'n_heads': 8,
      'dp': 8,
      'peak_mbs': {
        'mpi': 16,
        'capella': 16,
        'alpha': 8,
      },
      'max_tokens_billions': 15,
      'num_token_budgets': 5,
      'beta2': 0.95,
    },
    '1B': {
      'total_params': 1002203904,
      'non_embedding_params': 924936960,
      'd_model': 1536,
      'n_layers': 28,
      'n_heads': 16,
      'dp': 8,
      'peak_mbs': {
        'mpi': 4,
        'capella': 4,
        'alpha': 2,
      },
      'max_tokens_billions': 15,
      'num_token_budgets': 5,
      'beta2': 0.95,
    },
  },
  'batch_sizes': [16, 32, 64, 128, 256, 512],
  'batch_size_vs_token_budget_strategy': {
    'staggered_grid': {
      '0.5B': [16, 32, 64, 128],
      '1.0B': [16, 32, 64, 128],
      '3.0B': [32, 64, 128, 256],
      '7.5B': [64, 128, 256, 512],
      '15.0B': [64, 128, 256, 512],
    },
    'staggered_runs': {
      16: '1.0B',
      32: '3.0B',
      64: '15.0B',
      128: '15.0B',
      256: '15.0B',
      512: '15.0B',
    },
  },
  'learning_rates': [0.00025, 0.0005, 0.001, 0.002, 0.004, 0.008],
  'gradient_accumulation_steps': [1, 2, 4, 8],
  'warmup_steps': 2000,
  'cooldown_steps': 4000,
  'seq_len': 2048,
  'throughput_analysis_steps': 100,
}

SCALING_RESULTS_FOLDER = {
  'mpi': '/fast/jsingh/projects/fastlm/june/results/',
  'capella': '/data/horse/ws/jasi149i-fastlm/results',
  'alpha': '/data/horse/ws/jasi149i-fastlm/results',
}

LR_FLOAT_TO_STR_MAP = {0.00025: '25e-5', 0.0005: '5e-4', 0.001: '1e-3', 0.002: '2e-3', 0.004: '4e-3', 0.008: '8e-3'}
PARAM_SCALE_ID_TO_MEM_MAP = {'20M': 32, '50M': 64, '150M': 72, '300M': 96}
TOKENIZERS = {
  'mpi': '/fast/jsingh/saved_tokenizers/better-gpt2',
  'capella': '/data/horse/ws/jasi149i-fastlm/tokenizers/gpt2',
  'alpha': '/data/horse/ws/jasi149i-fastlm/tokenizers/gpt2',
}
DATA_PREFIXES = {
  'mpi': '/fast/jsingh/data',
  'capella': '/data/horse/ws/jasi149i-fastlm/data',
  'alpha': '/data/horse/ws/jasi149i-fastlm/data',
}
WANDB_DIR_PREFIXES = {
  'mpi': '/fast/jsingh/projects/fastlm/wandb_logs/june/better',
  'capella': '/data/horse/ws/jasi149i-fastlm/wandb_logs',
  'alpha': '/data/horse/ws/jasi149i-fastlm/wandb_logs',
}

DEFAULT_CONFIG = {
  'deterministic': False,
  'seed': 123,
  'measure_throughput': False,
  'trainset_path': 'nemotron-cc-sample-mtsynth/tokenized_gpt2/ctx_2048/train',
  'vocab_size': 50304,
  'seq_len': 2048,
  'intra_doc_masking': True,
  'sampler': 'sequential',
  'sampler_seed': None,
  'num_workers': 4,
  'eval': True,
  'validset_path': 'nemotron-cc-sample-mtsynth/tokenized_gpt2/ctx_2048/valid',
  'num_evals': 20,
  'eval_every_steps': -1,
  # MODEL
  'arch_id': 'attn',
  'param_scale_id': '20M',
  'model': 'transformer',
  'd_model': 256,
  'mlp_class': 'glu',
  'expand': '3.0',
  'n_layers': 8,
  'n_heads': 4,
  'rms_norm': True,
  'tie_embeddings': True,
  'torch_compile': True,
  'token_mixer': 'attn',
  'hybrid_mixer_ratio': 1,
  'layer_norm_scaling': False,
  'residual_connection': 'add',
  'attn_gate': True,
  'attn_qk_norm': True,
  'gdn_conv_size': 4,
  'gdn_gate': True,
  'gdn_neg_eigval': True,
  # TRAINING
  'token_budget_id': '3.0B',
  'steps_budget': -1,
  'global_batch_size': 32,
  'micro_batch_size': -1,
  'grad_accumulation_steps': 1,
  'dtype': 'bfloat16',
  # OPTIMIZER
  'optim': 'adamw',
  'fused_optim': True,
  'lr': 1e-3,
  'weight_decay': 0.1,
  'beta1': 0.9,
  'beta2': 0.99,
  'grad_clip': 1.0,
  # SCHEDULER
  'scheduler': 'wsd',
  'warmup_steps': 2000,
  'cooldown_steps': 0.2,
  'lr_start': 0.0,
  'lr_end': 1e-5,
  'lr_end_pct': None,
  # EXPERIMENT
  'log_every_steps': 1,
  'print_progress': True,
  # WANDB
  'use_wandb': True,
  'wandb_mode': 'offline',
  'wandb_project': 'hparam-sweep',
  'wandb_entity': 'msc-thesis-jaisidh',
  'wandb_dir': 'some_wandb_dir_location',
  'wandb_run_name': 'attn-20M_gbs-32',
  'exp_name': 'attn-20M_gbs-32',
  # RESUME
  'resume': False,
  'resume_step': None,
  'resume_exp_name': None,
  'cooldown_only': False,
  # SAVING
  'save_last_checkpoint': True,
  'save_intermediate_checkpoints': True,
  'save_every_steps': 500,
}
